routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::group(['middleware'=>['auth']], function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::middleware(['login.role:admin'])->group(function(){
        // Companies route
        Route::resource('/companies', CompanyController::class);
        Route::get('/comapnies/getCompanies', [CompanyController::class, 'getCompanies'])->name('companies.getCompanies');

        // Employees route
        Route::get('/employees/getEmployees', [EmployeeController::class, 'getEmployees'])->name('employees.getEmployees');
        Route::resource('/employees', EmployeeController::class);
    });
    
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Company;
use App\Http\Requests\CompanyRequest;
use Exception;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('companies.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form_action = route('companies.store');
        $page_title = 'Create Company';
        $page_type = 'create';
        return view('companies.form', [
            'form_action'=>$form_action,
            'page_title'=>$page_title,
            'page_type'=>$page_type
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        $newCompany = $request->validated();
        try {
            // save new company data
            $imageName = '';
            if ($request->hasFile('logo') && $request->file('logo')->isValid()) {
                $imageName = time().'.'.$request->logo->extension();
                $request->logo->move(public_path('storage'), $imageName);
                $imageName;
            }
            $company = new Company();
            $company->name = $newCompany['name'];
            $company->email = $newCompany['email'];
            $company->logo = $imageName;
            $company->website = $newCompany['website'];
            $company->save();

            if ($company) {
                error_log('success');
                return redirect()->route('companies.index')->with('success','New Company created');
            }else {
                error_log('failed');
                return redirect()->route('companies.index')->with('error','New Company failed to create');
            }
        }catch (Exception $e) {
            return redirect()->back()->with('error', $e);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::find($id);
        return json_encode($company);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        $form_action = route('companies.update', $company);
        $page_title = 'Edit Company';
        $page_type = 'edit';
        return view('companies.form', [
            'company'=>$company,
            'form_action'=>$form_action,
            'page_title'=>$page_title,
            'page_type'=>$page_type
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, $id)
    {
        $newCompany = $request->validated();
        $company = Company::find($id);
        try {
            // save new company data
            $imageName = $company->logo;
            if ($request->hasFile('logo') && $request->file('logo')->isValid()) {
                $imageName = time().'.'.$request->logo->extension();
                $request->logo->move(public_path('storage'), $imageName);
                $imageName;
            }
            $company->name = $newCompany['name'];
            $company->email = $newCompany['email'];
            $company->logo = $imageName;
            $company->website = $newCompany['website'];
            $company->save();

            if ($company) {
                error_log('success');
                return redirect()->route('companies.index')->with('success','Company has been successfully updated');
            }else {
                error_log('failed');
                return redirect()->route('companies.index')->with('error','Company failed to update');
            }
        }catch (Exception $e) {
            return redirect()->back()->with('error', $e);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $company = Company::find($id);
            $company->delete();
            return redirect()->route('companies.index')->with('success', 'Company has been successfully deleted');
        } catch (Exception $e){
            return redirect()->route('companies.index')->with('error', 'Company failed to delete');
        }
    }

    /**
     * AJAX to get companies for Data Table
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function getCompanies(Request $request)
    {
        $draw = $request->get('draw');
        $start = $request->get("start");
        $rowperpage = $request->get("length"); // total number of rows per page

        $columnIndex_arr = $request->get('order');
        $columnName_arr = $request->get('columns');
        $order_arr = $request->get('order');
        $search_arr = $request->get('search');

        $columnIndex = $columnIndex_arr[0]['column']; // Column index
        $columnName = $columnName_arr[$columnIndex]['data']; // Column name
        $columnName = $columnName == 0 ? 'name' : $columnName;
        $columnSortOrder = $order_arr[0]['dir']; // asc or desc
        $searchValue = $search_arr['value']; // Search value


        // Total records
        $totalRecords = Company::select('count(*) as allcount')->count();
        $totalRecordswithFilter = Company::select('count(*) as allcount')->where('name', 'like', '%' . $searchValue . '%')->count();

        $records = Company::orderBy($columnName, $columnSortOrder)
                ->where('companies.name', 'like', '%' . $searchValue . '%')
                ->orWhere('companies.email', 'like', '%' . $searchValue . '%')
                ->select('companies.*')
                ->skip($start)
                ->take($rowperpage)
                ->get();


        $data = array();

        foreach ($records as $record) {
            $data[] = array(
                'id' => $record->id,
                'name' => $record->name,
                'email' => $record->email,
                'logo' => "<img src='storage/$record->logo' loading='lazy' class='img-thumbnail'>",
                'website' => "<a href='$record->website' target='_blank'>$record->website</a>",
                'action'=>"<a href='/companies/$record->id/edit' class='btn btn-primary mt-1'>Edit</a> <button data-target='/companies/$record->id' data-name='$record->name' class='btn btn-danger delete mt-1'>Delete</button>"
            );
        }

        $response = array(
            "draw" => intval($draw),
            "iTotalRecords" => $totalRecords,
            "iTotalDisplayRecords" => $totalRecordswithFilter,
            'aaData' => $data,
        );
        echo json_encode($response);
    }
}

resources/views/companies/form.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{$page_title}}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">{{$page_title}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{$page_title}}</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                        <i class="fas fa-minus"></i></button>
                </div>
            </div>
            <div class="card-body">
                <form action="{{$form_action}}" method='POST' enctype="multipart/form-data">
                    @if ($page_type=='edit')
                    @method('PUT')
                    @endif
                    @csrf
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="name">Company Name</label>
                                <input type="text" name='name' class='form-control @error(' name')is-invalid @enderror'
                                    value="{{$company->name??old('company')}}" placeholder="Company Name" required>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="email">Company Email</label>
                                <input type="email" name='email' class='form-control'
                                    value="{{$company->email??old('email')}}" placeholder="e.g. test@laravel.com">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="logo">Company Logo</label>
                                <input type="file" name="logo" id="logo" class="form-control" accept="image/*">
                                <div class="row" style="margin-top:5px">
                                    <div class="col-md-3">
                                        <img src="{{ isset($company->logo)?asset('storage/'.$company->logo):asset('img/no-image.jpg') }}"
                                            id='display-image' alt="no-image" srcset="" class="img-thumbnail">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="website">Company Website</label>
                                <input type="text" name='website' class='form-control'
                                    value="{{$company->website??old('website')}}"
                                    placeholder="e.g. http://laraveltest.com">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group float-right mt-3">
                                <a href="{{ route('companies.index') }}" class="btn btn-danger">Cancel</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
@endsection

@section('script')
<script>
    $("body").on("change", "#logo", function () {
        var defaultsrc = '/img/no-image.jpg';
        var input = this;
        var url = $(this).val();
        console.log(url);
        var ext = url.substring(url.lastIndexOf(".") + 1).toLowerCase();
        if (
            input.files &&
            input.files[0] &&
            (ext == "gif" || ext == "png" || ext == "jpeg" || ext == "jpg")
        ) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#display-image").attr("src", e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }else {
            $("#display-image").attr("src", defaultsrc);
        }
    });
</script>
@endsection

resources/views/companies/list.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Companies</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Companies</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Companies</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                        <i class="fas fa-minus"></i></button>
                </div>
            </div>
            <div class="card-body">
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <a href="#" class="close" id='close-alert' data-dismiss="alert">&times;</a>
                    <p>{{ $message }}</p>
                </div>
                @endif
                @if ($message = Session::get('error'))
                <div class="alert alert-danger">
                    <a href="#" class="close" id='close-alert' data-dismiss="alert">&times;</a>
                    <p>{{ $message }}</p>
                </div>
                @endif
                <div class="row">
                    <div class="col-3 mb-3">
                        <a href="{{ route('companies.create') }}" class="btn btn-primary"><i
                                class="fa fa-plus"></i>&nbsp;Create&nbspCompanies</a>
                    </div>
                    <div class="col-12">
                        <table class="table table-bordered data-table">
                            <thead>
                                <tr>
                                    <th>Index</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Logo</th>
                                    <th>Website</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                        <form action="" id='form-delete' method="POST">
                            @method('DELETE')
                            @csrf
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>

<div class="modal fade" id="modal-delete">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete Company</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id='delete-text'></p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id='delete-button'>Delete</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
@endsection

@section('script')
<script>
    $(function(){

        $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            autoWidth: false,
            ajax: "{{ route('companies.getCompanies') }}",
            columns: [
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'email', name: 'email'},
                {data: 'logo', name: 'logo'},
                {data: 'website', name: 'website'},
                  {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        })

        $('body').on('click','.delete', function(){
            let target = $(this).data('target')
            let name = $(this).data('name')
            console.log(target)
            $('#delete-text').text('Are you sure you want to delete the '+name+' company?')
            $('#modal-delete').modal('show')
            $('#form-delete').attr('action',target)
        })

        $('#delete-button').click(function(){
            $('#form-delete').submit()
        })

    })
</script>
@endsection