routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::group(['middleware'=>['auth']], function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::middleware(['login.role:admin'])->group(function(){
        // Companies route
        Route::resource('/companies', CompanyController::class);
        Route::get('/comapnies/getCompanies', [CompanyController::class, 'getCompanies'])->name('companies.getCompanies');

        // Employees route
        Route::get('/employees/getEmployees', [EmployeeController::class, 'getEmployees'])->name('employees.getEmployees');
        Route::resource('/employees', EmployeeController::class);
    });
    
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    public function company(){
        return $this->belongsTo('App\Models\Company', 'company_id', 'id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeRequest;
use App\Mail\NewEmployee;
use App\Models\Company;
use App\Models\Employee;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('employees.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        $form_action = route('employees.store');
        $page_title = 'Create Employee';
        $page_type = 'create';
        return view('employees.form', [
            'form_action'=>$form_action,
            'page_title'=>$page_title,
            'page_type'=>$page_type,
            'companies'=>$companies
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $newEmployee = $request->validated();
        // dd($newEmployee);
        // try{
            $employee = new Employee();
            $employee->first_name = $newEmployee['first_name'];
            $employee->last_name = $newEmployee['last_name'];
            $employee->company_id = $newEmployee['company'];
            $employee->email = $newEmployee['email'];
            $employee->phone = $newEmployee['phone'];
            $employee->save();
            error_log('saved');
            error_log($employee->company->email);
            Mail::to($employee->company->email)->send(new NewEmployee());
            error_log('send');

            if ($employee){
                error_log('success');
                return redirect()->route('employees.index')->with('success','New Employee created');
            }else {
                error_log('failed');
                return redirect()->route('employees.index')->with('error','New Employee failed to create');
            }
        // }catch (Exception $e){
        //     return redirect()->back()->with('error', $e);
        // }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        $companies = Company::all();
        $form_action = route('employees.update', $employee);
        $page_title = 'Edit Employee';
        $page_type = 'edit';
        return view('employees.form', [
            'form_action'=>$form_action,
            'page_title'=>$page_title,
            'page_type'=>$page_type,
            'companies'=>$companies,
            'employee'=>$employee
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, $id)
    {
        $newEmployee = $request->validated();
        // dd($newEmployee);
        try{
            $employee = Employee::find($id);
            $employee->first_name = $newEmployee['first_name'];
            $employee->last_name = $newEmployee['last_name'];
            $employee->company_id = $newEmployee['company'];
            $employee->email = $newEmployee['email'];
            $employee->phone = $newEmployee['phone'];
            $employee->save();

            if ($employee){
                error_log('success');
                return redirect()->route('employees.index')->with('success','Employee has been successfully updated');
            }else {
                error_log('failed');
                return redirect()->route('employees.index')->with('error','Employee failed to update');
            }
        }catch (Exception $e){
            return redirect()->back()->with('error', $e);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $employee = Employee::find($id);
            $employee->delete();
            return redirect()->route('employees.index')->with('success', 'Employee has been successfully deleted');
        } catch (Exception $e){
            return redirect()->route('employees.index')->with('error', 'Employee failed to delete');
        }
    }


    /**
     * AJAX to get companies for Data Table
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function getEmployees(Request $request)
    {
        // return 'test';
        // dd('test');
        $draw = $request->get('draw');
        $start = $request->get("start");
        $rowperpage = $request->get("length"); // total number of rows per page

        $columnIndex_arr = $request->get('order');
        $columnName_arr = $request->get('columns');
        $order_arr = $request->get('order');
        $search_arr = $request->get('search');

        $columnIndex = $columnIndex_arr[0]['column']; // Column index
        $columnName = $columnName_arr[$columnIndex]['data']; // Column name
        $columnName = $columnName == 0 ? 'first_name' : $columnName;
        $columnSortOrder = $order_arr[0]['dir']; // asc or desc
        $searchValue = $search_arr['value']; // Search value


        // Total records
        $totalRecords = Employee::select('count(*) as allcount')->count();
        $totalRecordswithFilter = Employee::select('count(*) as allcount')->where('first_name', 'like', '%' . $searchValue . '%')->count();

        $records = Employee::orderBy($columnName, $columnSortOrder)
                ->where('employees.first_name', 'like', '%' . $searchValue . '%')
                ->orWhere('employees.last_name', 'like', '%' . $searchValue . '%')
                ->orWhere('employees.email', 'like', '%' . $searchValue . '%')
                ->orWhere('employees.phone', 'like', '%' . $searchValue . '%')
                ->select('employees.*')
                ->skip($start)
                ->take($rowperpage)
                ->get();

        $data = array();

        foreach ($records as $record) {
            $data[] = array(
                'id' => $record->id,
                'fullname'=> $record->first_name.' '.$record->last_name,
                'company'=> "<button class='btn btn-primary view' data-target='/companies/$record->company_id'>".$record->company->name."</button>",
                'email'=>$record->email,
                'phone'=>$record->phone,
                'action'=>"<a href='/employees/$record->id/edit' class='btn btn-primary mt-1'>Edit</a> <button data-target='/employees/$record->id' data-name='$record->name' class='btn btn-danger delete mt-1'>Delete</button>"
            );
        }

        $response = array(
            "draw" => intval($draw),
            "iTotalRecords" => $totalRecords,
            "iTotalDisplayRecords" => $totalRecordswithFilter,
            'aaData' => $data,
        );
        echo json_encode($response);
        // return $response;
    }
}

resources/views/employees/form.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{$page_title}}</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">{{$page_title}}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{$page_title}}</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                        <i class="fas fa-minus"></i></button>
                </div>
            </div>
            <div class="card-body">
                <form action="{{$form_action}}" method='POST' enctype="multipart/form-data">
                    @if ($page_type=='edit')
                    @method('PUT')
                    @endif
                    @csrf
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="first_name">First Name</label>
                                <input type="text" name='first_name' class='form-control @error('first_name')is-invalid @enderror'
                                    value="{{$employee->first_name??old('first_name')}}" placeholder="First Name" required>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="last_name">Last Name</label>
                                <input type="text" name='last_name' class='form-control @error('last_name')is-invalid @enderror'
                                    value="{{$employee->last_name??old('last_name')}}" placeholder="Last Name" required>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="company">Company</label>
                                <select name="company" id="company" class="form-control @error('company')is-invalid @enderror" required>
                                    <option value="">- Select Company -</option>
                                    @foreach ($companies as $company)
                                    <option value="{{$company->id}}" {{ isset($employee->company_id)?($employee->company_id==$company_id?'selected':''):(old('company')==$company->id?'selected':'') }}>{{$company->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" name='email' class='form-control @error('email')is-invalid @enderror'
                                    value="{{$employee->email??old('email')}}" placeholder="e.g. test@laravel.com">
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="phone">Phone</label>
                                <input type="text" name='phone' class='form-control @error('phone')is-invalid @enderror'
                                    value="{{$employee->phone??old('phone')}}" placeholder="Phone">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group float-right mt-3">
                                <a href="{{ route('employees.index') }}" class="btn btn-danger">Cancel</a>
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>
@endsection

resources/views/employees/list.blade.php
@extends('layouts.app')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Employees</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Employees</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Employees</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                        <i class="fas fa-minus"></i></button>
                </div>
            </div>
            <div class="card-body">
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <a href="#" class="close" id='close-alert' data-dismiss="alert">&times;</a>
                    <p>{{ $message }}</p>
                </div>
                @endif
                @if ($message = Session::get('error'))
                <div class="alert alert-danger">
                    <a href="#" class="close" id='close-alert' data-dismiss="alert">&times;</a>
                    <p>{{ $message }}</p>
                </div>
                @endif
                <div class="row">
                    <div class="col-3 mb-3">
                        <a href="{{ route('employees.create') }}" class="btn btn-primary"><i
                                class="fa fa-plus"></i>&nbsp;Create&nbsp;Employees</a>
                    </div>
                    <div class="col-12">
                        <table class="table table-bordered data-table">
                            <thead>
                                <tr>
                                    <th>Index</th>
                                    <th>Full Name</th>
                                    <th>Company</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                        <form action="" id='form-delete' method="POST">
                            @method('DELETE')
                            @csrf
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
</div>

<div class="modal fade" id="modal-delete">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete Employee</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p id='delete-text'></p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id='delete-button'>Delete</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal fade" id="modal-view">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id='modal-view-title'></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row mb-3">
                    <div class="col-12 text-center">
                        <img src="" alt="company logo" id='company-logo' class="img-thumbnail mx-auto">
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <p><b>Name</b></p>
                    </div>
                    <div class="col-8">
                        <p id='company-name'></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <p><b>Email</b></p>
                    </div>
                    <div class="col-8">
                        <p id='company-email'></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <p><b>Website</b></p>
                    </div>
                
                    <div class="col-8">
                        <p id='company-website'></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger" id='delete-button'>Delete</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
@endsection

@section('script')
<script>
    $(function(){
        $('.data-table').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            autoWidth: false,
            ajax: "{{ route('employees.getEmployees') }}",
            columns: [
                {data: 'id', name: 'id'},
                {data: 'fullname', name: 'fullname'},
                {data: 'company', name: 'company'},
                {data: 'email', name: 'email'},
                {data: 'phone', name: 'phone'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        })

        $('body').on('click','.delete', function(){
            let target = $(this).data('target')
            let name = $(this).data('name')
            console.log(target)
            $('#delete-text').text('Are you sure you want to delete the '+name+'?')
            $('#modal-delete').modal('show')
            $('#form-delete').attr('action',target)
        })

        $('body').on('click', '.view', function() {
            let target = $(this).data('target')
            $.ajax({
                url: target,
                method: 'GET',
                success:function(data){
                    data = JSON.parse(data)
                    console.log(data)
                    $('#company-logo').attr('src', 'storage/'+data.logo)
                    $('#company-name').text(data.name)
                    $('#company-email').text(data.email)
                    $('#company-website').text(data.website)
                    $('#modal-view-title').text(data.name+' Company')
                }
            })
            $('#modal-view').modal('show')
        })

        $('#delete-button').click(function(){
            $('#form-delete').submit()
        })
    })
</script>
@endsection